name: khafif_food_ordering_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  # awesome_dialog:  
  bot_toast: ^4.0.3
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  file_picker: ^6.1.1
  firebase_analytics: ^10.4.4
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.16.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_polyline_points: null
  flutter_sliding_up_panel: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  geocoding: ^2.1.0
  get: ^4.6.5
  google_maps_flutter: ^2.3.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  http_parser: ^4.0.2
  hyperpay_plugin: ^2.0.8
  image_picker: ^1.1.1
  intl: ^0.17.0
  label_marker: ^1.0.1
  location: ^5.0.0
  lottie: ^3.0.0
  mime: ^1.0.4
  pin_code_fields: ^8.0.1
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  rating_dialog: ^2.0.4
  shared_preferences: ^2.1.0
  shimmer: ^3.0.0
  sizer: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  timer_count_down: ^2.2.2
  url_launcher: ^6.1.10
  scroll_loop_auto_scroll: ^0.0.2
  auto_scroll_text: ^0.0.7
  geolocator: ^11.0.0
  
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/

  #   - images/a_dot_ham.jpeg
  # An image asset can rePfer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Baloo 2
      fonts:
        - asset: assets\fonts\Baloo2-VariableFont_wght.ttf
        - asset: assets/fonts/Baloo2Bold.ttf
          weight: 700
        - asset: assets/fonts/Baloo2Regular.ttf
          weight: 400
        - asset: assets/fonts/Baloo2SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Baloo2Medium.ttf
          weight: 500
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
