// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTbYhYZywMAMKgW7XtCp9iT4eKzO5UBM',
    appId: '1:584610308731:web:180c397f2f5069f54ef8de',
    messagingSenderId: '584610308731',
    projectId: 'khafif-food-ordering',
    authDomain: 'khafif-food-ordering.firebaseapp.com',
    storageBucket: 'khafif-food-ordering.appspot.com',
    measurementId: 'G-G3FFVVD20J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEoC3PjMNLOOuumoIU39nLyZ5FAmJi5Qg',
    appId: '1:584610308731:android:e1327d3cb77ec3fd4ef8de',
    messagingSenderId: '584610308731',
    projectId: 'khafif-food-ordering',
    storageBucket: 'khafif-food-ordering.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGCWOXbA2SJldtyaKXvPoSkdY19Z98wv4',
    appId: '1:584610308731:ios:fabd0045e83314884ef8de',
    messagingSenderId: '584610308731',
    projectId: 'khafif-food-ordering',
    storageBucket: 'khafif-food-ordering.appspot.com',
    androidClientId: '584610308731-vkbdv7fvj76g03ou2t27clf2rudg07l3.apps.googleusercontent.com',
    iosClientId: '584610308731-l17va0a3vembkdqf3di3hks3jdfadfc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.khafifFoodOrderingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGCWOXbA2SJldtyaKXvPoSkdY19Z98wv4',
    appId: '1:584610308731:ios:8a2df1bdd6550b594ef8de',
    messagingSenderId: '584610308731',
    projectId: 'khafif-food-ordering',
    storageBucket: 'khafif-food-ordering.appspot.com',
    androidClientId: '584610308731-vkbdv7fvj76g03ou2t27clf2rudg07l3.apps.googleusercontent.com',
    iosClientId: '584610308731-k63i8p7tslc9epq8oqrhdli58lbcsp8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.khafifFoodOrderingApplication.RunnerTests',
  );
}
