// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTbYhYZywMAMKgW7XtCp9iT4eKzO5UBM',
    appId: '1:584610308731:web:180c397f2f5069f54ef8de',
    messagingSenderId: '584610308731',
    projectId: 'khafif-food-ordering',
    authDomain: 'khafif-food-ordering.firebaseapp.com',
    storageBucket: 'khafif-food-ordering.appspot.com',
    measurementId: 'G-G3FFVVD20J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfirdCa7K-WxWGzu3fMKF_iAzA_iieeq0',
    appId: '1:486734582737:android:297d65d7c3c4e4a04186f0',
    messagingSenderId: '486734582737',
    projectId: 'khafif-9797b',
    storageBucket: 'khafif-9797b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD984DdZsJpPkNpLFEvThI83duhb_qj83Y',
    appId: '1:486734582737:ios:a6a4435e49fd344c4186f0',
    messagingSenderId: '486734582737',
    projectId: 'khafif-9797b',
    storageBucket: 'khafif-9797b.appspot.com',
    iosBundleId: 'com.example.khafifFoodOrderingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD984DdZsJpPkNpLFEvThI83duhb_qj83Y',
    appId: '1:486734582737:ios:42c9b59b9461f2714186f0',
    messagingSenderId: '486734582737',
    projectId: 'khafif-9797b',
    storageBucket: 'khafif-9797b.appspot.com',
    iosBundleId: 'com.khafif.app',
  );

}