// import 'package:flutter/material.dart';
// import 'package:get/get.dart';
// import 'package:khafif_food_ordering_application/src/core/utility/general_utils.dart';

// /// Helper class for managing themes and colors.
// class ThemeHelper {
//   // The current app theme
//   final _appTheme = storage.getAppTheme();

// // A map of custom color themes supported by the app
//   final Map<String, PrimaryColors> _supportedCustomColor = {
//     'primary': PrimaryColors()
//   };

// // A map of color schemes supported by the app
//   final Map<String, ColorScheme> _supportedColorScheme = {
//     'primary': ColorSchemes.primaryColorScheme
//   };

//   /// Changes the app theme to [newTheme].
//   void changeTheme(bool newTheme) {
//     storage.setAppTheme(dark: newTheme);
//     Get.forceAppUpdate();
//   }

//   /// Returns the primary colors for the current theme.
//   PrimaryColors _getThemeColors() {
//     //throw exception to notify given theme is not found or not generated by the generator
//     if (!_supportedCustomColor.containsKey(_appTheme)) {
//       throw Exception(
//           "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
//     }
//     //return theme from map

//     return _supportedCustomColor[_appTheme] ?? PrimaryColors();
//   }

//   /// Returns the current theme data.
//   ThemeData _getThemeData() {
//     //throw exception to notify given theme is not found or not generated by the generator
//     if (!_supportedColorScheme.containsKey(_appTheme)) {
//       throw Exception(
//           "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
//     }
//     //return theme from map

//     var colorScheme =
//         _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
//     return ThemeData(
//       visualDensity: VisualDensity.standard,
//       colorScheme: colorScheme,
//       textTheme: TextThemes.textTheme(colorScheme),
//       scaffoldBackgroundColor: appTheme.gray10001,
//       elevatedButtonTheme: ElevatedButtonThemeData(
//         style: ElevatedButton.styleFrom(
//           backgroundColor: colorScheme.primary,
//           shape: RoundedRectangleBorder(
//             borderRadius: BorderRadius.circular(8),
//           ),
//           visualDensity: const VisualDensity(
//             vertical: -4,
//             horizontal: -4,
//           ),
//           padding: EdgeInsets.zero,
//         ),
//       ),
//       outlinedButtonTheme: OutlinedButtonThemeData(
//         style: OutlinedButton.styleFrom(
//           backgroundColor: Colors.transparent,
//           side: BorderSide(
//             color: appTheme.gray300,
//             width: 1,
//           ),
//           shape: RoundedRectangleBorder(
//             borderRadius: BorderRadius.circular(8),
//           ),
//           visualDensity: const VisualDensity(
//             vertical: -4,
//             horizontal: -4,
//           ),
//           padding: EdgeInsets.zero,
//         ),
//       ),
//       radioTheme: RadioThemeData(
//         fillColor: MaterialStateColor.resolveWith((states) {
//           if (states.contains(MaterialState.selected)) {
//             return colorScheme.primary;
//           }
//           return colorScheme.onSurface;
//         }),
//         visualDensity: const VisualDensity(
//           vertical: -4,
//           horizontal: -4,
//         ),
//       ),
//       checkboxTheme: CheckboxThemeData(
//         fillColor: MaterialStateColor.resolveWith((states) {
//           if (states.contains(MaterialState.selected)) {
//             return colorScheme.primary;
//           }
//           return colorScheme.onSurface;
//         }),
//         side: const BorderSide(
//           width: 1,
//         ),
//         visualDensity: const VisualDensity(
//           vertical: -4,
//           horizontal: -4,
//         ),
//       ),
//       dividerTheme: DividerThemeData(
//         thickness: 1,
//         space: 1,
//         color: appTheme.gray30002,
//       ),
//     );
//   }

//   /// Returns the primary colors for the current theme.
//   PrimaryColors themeColor() => _getThemeColors();

//   /// Returns the current theme data.
//   ThemeData themeData() => _getThemeData();
// }

// /// Class containing the supported text theme styles.
// class TextThemes {
//   static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
//         bodyLarge: const TextStyle(
//           color: Color(0XFF231F20),
//           fontSize: 16,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w400,
//         ),
//         bodyMedium: TextStyle(
//           color: appTheme.gray600,
//           fontSize: 14,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w400,
//         ),
//         bodySmall: TextStyle(
//           color: appTheme.gray60002,
//           fontSize: 12,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w400,
//         ),
//         displayMedium: const TextStyle(
//           color: Color(0XFFFFFFFF),
//           fontSize: 40,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w700,
//         ),
//         displaySmall: const TextStyle(
//           color: Color(0XFF231F20),
//           fontSize: 36,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w600,
//         ),
//         headlineLarge: const TextStyle(
//           color: Color(0XFFFFFFFF),
//           fontSize: 30,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w700,
//         ),
//         headlineMedium: TextStyle(
//           color: appTheme.gray90007,
//           fontSize: 28,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w700,
//         ),
//         headlineSmall: TextStyle(
//           color: appTheme.gray90004,
//           fontSize: 24,
//           fontFamily: 'Lato',
//           fontWeight: FontWeight.w400,
//         ),
//         labelLarge: TextStyle(
//           color: appTheme.gray90004,
//           fontSize: 12,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w600,
//         ),
//         labelMedium: TextStyle(
//           color: appTheme.gray90004,
//           fontSize: 10,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w600,
//         ),
//         labelSmall: TextStyle(
//           color: colorScheme.onPrimaryContainer,
//           fontSize: 8,
//           fontFamily: 'Montserrat',
//           fontWeight: FontWeight.w500,
//         ),
//         titleLarge: TextStyle(
//           color: appTheme.black90006,
//           fontSize: 20,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w600,
//         ),
//         titleMedium: TextStyle(
//           color: appTheme.black90006,
//           fontSize: 16,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w600,
//         ),
//         titleSmall: TextStyle(
//           color: appTheme.gray90004,
//           fontSize: 14,
//           fontFamily: 'Baloo 2',
//           fontWeight: FontWeight.w600,
//         ),
//       );
// }

// /// Class containing the supported color schemes.
// class ColorSchemes {
//   static const primaryColorScheme = ColorScheme.light(
//     // Primary colors
//     primary: Color(0XFFFFAA01),
//     primaryContainer: Color(0XFF333333),
//     secondaryContainer: Color(0XFFEAB308),

//     // Error colors
//     errorContainer: Color(0XFF73777E),
//     onError: Color(0XFFF1B71B),
//     onErrorContainer: Color(0XFF161103),

//     // On colors(text colors)
//     onPrimary: Color(0XFF1F1F1F),
//     onPrimaryContainer: Color(0XA2FFFFFF),
//   );
// }

// /// Class containing custom colors for a primary theme.
// class PrimaryColors {
//   // Amber
//   Color get amber100 => const Color(0XFFFFE9AE);
//   Color get amber400 => const Color(0XFFFFC529);

//   // Black
//   Color get black900 => const Color(0XFF130E00);
//   Color get black90001 => const Color(0XFF010F06);
//   Color get black90002 => const Color(0XFF02060D);
//   Color get black90003 => const Color(0XFF03070E);
//   Color get black90004 => const Color(0XFF100F0F);
//   Color get black90005 => const Color(0XFF06060B);
//   Color get black90006 => const Color(0XFF000000);

//   // Blue
//   Color get blue50 => const Color(0XFFDFEFFF);
//   Color get blue800 => const Color(0XFF2571BD);
//   Color get blue80001 => const Color(0XFF0C61B6);

//   // BlueGray
//   Color get blueGray100 => const Color(0XFFD9D9D9);
//   Color get blueGray10001 => const Color(0XFFCDCDCD);
//   Color get blueGray200 => const Color(0XFFB2B8BD);
//   Color get blueGray400 => const Color(0XFF8B9890);
//   Color get blueGray40001 => const Color(0XFF82878F);
//   Color get blueGray40002 => const Color(0XFF8588A6);
//   Color get blueGray40003 => const Color(0XFF848290);
//   Color get blueGray40004 => const Color(0XFF8C8994);
//   Color get blueGray50 => const Color(0XFFECEDEF);
//   Color get blueGray800 => const Color(0XFF2D3B48);
//   Color get blueGray900 => const Color(0XFF302B42);
//   Color get blueGray90001 => const Color(0XFF282F3E);
//   Color get blueGray90002 => const Color(0XFF292D32);
//   Color get blueGray90003 => const Color(0XFF2A353D);
//   Color get blueGray90033 => const Color(0X33252B55);

//   // DeepOrange
//   Color get deepOrangeA400 => const Color(0XFFFA4A0C);

//   // DeepPurple
//   Color get deepPurpleA100 => const Color(0XFFA894FF);
//   Color get deepPurpleA200 => const Color(0XFF8F6AF8);

//   // Gray
//   Color get gray100 => const Color(0XFFF4F4F8);
//   Color get gray10001 => const Color(0XFFF3F4F6);
//   Color get gray10002 => const Color(0XFFF1F6F9);
//   Color get gray10003 => const Color(0XFFF2F2F2);
//   Color get gray200 => const Color(0XFFF0F0F0);
//   Color get gray300 => const Color(0XFFE6E6E6);
//   Color get gray30001 => const Color(0XFFE4E4E7);
//   Color get gray30002 => const Color(0XFFDDDDDD);
//   Color get gray30003 => const Color(0XFFDADADA);
//   Color get gray400 => const Color(0XFFB6B6B6);
//   Color get gray40001 => const Color(0XFFC7C7C7);
//   Color get gray50 => const Color(0XFFF9F9F9);
//   Color get gray500 => const Color(0XFF9A9A9A);
//   Color get gray50001 => const Color(0XFF9C9C9C);
//   Color get gray50002 => const Color(0XFFA8A9AB);
//   Color get gray50003 => const Color(0XFF999999);
//   Color get gray50004 => const Color(0XFF999589);
//   Color get gray50005 => const Color(0XFF9D9D9D);
//   Color get gray600 => const Color(0XFF757C86);
//   Color get gray60001 => const Color(0XFF707B81);
//   Color get gray60002 => const Color(0XFF727272);
//   Color get gray60003 => const Color(0XFF717171);
//   Color get gray60004 => const Color(0XFF848484);
//   Color get gray60005 => const Color(0XFF757475);
//   Color get gray60006 => const Color(0XFF7C7C7D);
//   Color get gray60007 => const Color(0XFF717283);
//   Color get gray60028 => const Color(0X28787880);
//   Color get gray800 => const Color(0XFF4D4D4D);
//   Color get gray80001 => const Color(0XFF514F4F);
//   Color get gray80002 => const Color(0XFF4E4E4E);
//   Color get gray900 => const Color(0XFF382E0A);
//   Color get gray90001 => const Color(0XFF211B04);
//   Color get gray90002 => const Color(0XFF131B27);
//   Color get gray90003 => const Color(0XFF031028);
//   Color get gray90004 => const Color(0XFF231F20);
//   Color get gray90005 => const Color(0XFF0F1827);
//   Color get gray90006 => const Color(0XFF1A242F);
//   Color get gray90007 => const Color(0XFF182233);
//   Color get gray90008 => const Color(0XFF071731);

//   // GrayE
//   Color get gray300E5 => const Color(0XE5E1E1E4);

//   // Green
//   Color get green20011 => const Color(0X119AC3B5);
//   Color get green500 => const Color(0XFF34C759);
//   Color get green800 => const Color(0XFF287B45);
//   Color get greenA700 => const Color(0XFF06C170);

//   // Indigo
//   Color get indigoA400 => const Color(0XFF4154FF);

//   // LightGreen
//   Color get lightGreen50 => const Color(0XFFF4F3EB);

//   // Lime
//   Color get lime50 => const Color(0XFFFCFAEB);

//   // Orange
//   Color get orange300 => const Color(0XFFF8B940);
//   Color get orange30001 => const Color(0XFFF4BD4B);
//   Color get orangeA200 => const Color(0XFFFDA036);
//   Color get orangeA20001 => const Color(0XFFEA9C3F);
//   Color get orangeA700 => const Color(0XFFFC6A03);

//   // Red
//   Color get red300 => const Color(0XFFE5646E);
//   Color get red400 => const Color(0XFFF7524B);
//   Color get red500 => const Color(0XFFF14336);
//   Color get red50001 => const Color(0XFFEA4335);
//   Color get red600 => const Color(0XFFDF313A);
//   Color get red60001 => const Color(0XFFE63527);
//   Color get red60002 => const Color(0XFFEA2930);
//   Color get red60003 => const Color(0XFFE92830);
//   Color get redA200 => const Color(0XFFFC495F);
//   Color get redA20001 => const Color(0XFFFF5B5D);
//   Color get redA400 => const Color(0XFFFF0917);

//   // Yellow
//   Color get yellow300 => const Color(0XFFFDEF6B);
//   Color get yellow900 => const Color(0XFFF58322);
//   Color get yellow90001 => const Color(0XFFCE7526);
// }

// PrimaryColors get appTheme => ThemeHelper().themeColor();
// ThemeData get theme => ThemeHelper().themeData();
